
spring:
  cloud:
    gateway:
      routes:
      - id: msvc-products
        uri: lb://msvc-products
        predicates:
        - Path=/api/products/**
        # - Header=token, 12345
        # - Method=GET, POST
        # - Query=color
        # - Cookie=color, azul
        # - Header=Content-Type, application/json
        filters:
        - StripPrefix=2
        - name: SampleCookie
          args:
            message: Hola
            name: user
            value: Yael
      - id: msvc-items
        uri: lb://msvc-items
        predicates:
        - Path=/api/items/**
        filters:
        - StripPrefix=2
        - AddRequestHeader=token-request, hello123
        - AddResponseHeader=token-response, 1212331abc
        - AddRequestParameter=name, valor
        - SetResponseHeader=Content-Type, text/plain

